In [71]:
using StatsBase, Distributions, LinearAlgebra, XSim, JWAS, DataFrames, CSV, DelimitedFiles

In [72]:
#set genome information for chromosome

chrLength= 0.1  #length of each chromosome 
numChr   = 2    #number of chromosomes
nmarkers = 2000   #number of loci for each chromosome
nQTL     = 30 #number of QTL for each chromosomefects,mutRate);
build_genome(numChr,chrLength,nmarkers,nQTL)

In [73]:
# generate 4 generations

#generation 0
#generate founders
popSizeFounder = 100
sires = sampleFounders(popSizeFounder);
dams  = sampleFounders(popSizeFounder);

#random mating
ngen,popSize = 1,100
sires1,dams1,gen1 = sampleRan(popSize, ngen, sires, dams);

Sampling 100 animals into base population.
Sampling 100 animals into base population.
Generation     2: sampling    50 males and    50 females


In [74]:
ngen, popSize=1, 100
sires2,dams2,gen2 = sampleRan(popSize, ngen, sires1, dams1);

Generation     2: sampling    50 males and    50 females


In [75]:
ngen, popSize=1, 300
sires3,dams3,gen3 = sampleRan(popSize, ngen, sires2, dams2);

Generation     2: sampling   150 males and   150 females


In [76]:
ngen, popSize= 1, 1000
sires4,dams4,gen4 = sampleRan(popSize, ngen, sires3, dams3);


Generation     2: sampling   500 males and   500 females


In [77]:
ngen, popSize = 1, 1600
sires5, dams5, gen5 = sampleRan(popSize, ngen, sires4, dams4)

Generation     2: sampling   800 males and   800 females


(XSim.Cohort(XSim.Animal[Animal(XSim.Chromosome[Chromosome(Int64[], [291], [0.0]), Chromosome(Int64[], [155], [0.0])], XSim.Chromosome[Chromosome(Int64[], [345, 346], [0.0, 0.0270274]), Chromosome(Int64[], [173], [0.0])], Float64[], 1701, 1041, 1362, -9999.0, -9999.0, -9999.0), Animal(XSim.Chromosome[Chromosome(Int64[], [55], [0.0]), Chromosome(Int64[], [257, 103, 257, 373], [0.0, 0.0259667, 0.0917196, 0.0966567])], XSim.Chromosome[Chromosome(Int64[], [54], [0.0]), Chromosome(Int64[], [286, 372], [0.0, 0.000553448])], Float64[], 1702, 1141, 1376, -9999.0, -9999.0, -9999.0), Animal(XSim.Chromosome[Chromosome(Int64[], [345], [0.0]), Chromosome(Int64[], [108], [0.0])], XSim.Chromosome[Chromosome(Int64[], [115], [0.0]), Chromosome(Int64[], [84, 346], [0.0, 0.0355672])], Float64[], 1703, 894, 1463, -9999.0, -9999.0, -9999.0), Animal(XSim.Chromosome[Chromosome(Int64[], [368, 312], [0.0, 0.0579838]), Chromosome(Int64[], [84], [0.0])], XSim.Chromosome[Chromosome(Int64[], [323], [0.0]), Chromos

In [78]:
#collect the animals data 
animals = concatCohorts(sires5,dams5);

In [79]:
#get genotypes
M = getOurGenotypes(animals);
#get phenotypes
Phen = getOurPhenVals(animals, 1.0);
#get pedigree
Ped = getPedigree(animals);

In [80]:
#write out
Phenotypes = DataFrame();
Phenotypes[:y] = Phen;

CSV.write("Phenotypes-ssbr1.txt", Phenotypes)
writedlm("Genotypes-ssbr1.txt", M)
writedlm("Pedigree-ss.txt", Ped)

In [65]:
Phenotypes

1600×1 DataFrame
│ Row  │ y         │
│      │ Float64   │
├──────┼───────────┤
│ 1    │ -1.49799  │
│ 2    │ -15.441   │
│ 3    │ -5.56585  │
│ 4    │ -3.31998  │
│ 5    │ -11.5113  │
│ 6    │ -2.47375  │
│ 7    │ -6.43256  │
│ 8    │ 1.82927   │
│ 9    │ -6.10564  │
│ 10   │ -8.60791  │
⋮
│ 1590 │ -12.8429  │
│ 1591 │ -0.713308 │
│ 1592 │ -5.92655  │
│ 1593 │ -3.1855   │
│ 1594 │ -4.7209   │
│ 1595 │ -1.49749  │
│ 1596 │ -12.4165  │
│ 1597 │ -9.46714  │
│ 1598 │ -24.3422  │
│ 1599 │ -6.64066  │
│ 1600 │ -2.48019  │

In [37]:
#output the simulated animals data as pedigree, phenotype, genotype and maps
outputPedigree(animals, "simulated-animal-data")

In [38]:
outputPedigree(animals, "simulated_2")

In [39]:
getPedigree(animals)

200×3 Array{Int64,2}:
   1  0  0
   2  0  0
   3  0  0
   4  0  0
   5  0  0
   6  0  0
   7  0  0
   8  0  0
   9  0  0
  10  0  0
  11  0  0
  12  0  0
  13  0  0
   ⋮      
 189  0  0
 190  0  0
 191  0  0
 192  0  0
 193  0  0
 194  0  0
 195  0  0
 196  0  0
 197  0  0
 198  0  0
 199  0  0
 200  0  0

┌ Warning: Deprecated syntax ``?` used as an identifier`.
└ @ nothing none:1
┌ Warning: Deprecated syntax ``?` used as an identifier`.
└ @ nothing none:1


In [40]:
?getPedigree

search: getPedigree get_pedigree



No documentation found.

`XSim.getPedigree` is a `Function`.

```
# 1 method for generic function "getPedigree":
[1] getPedigree(animals::XSim.Cohort) in XSim at C:\Users\adhal\.julia\packages\XSim\XfykA\src\cohort\checkCohort.jl:10
```


In [69]:
?parse


search: parse tryparse partialsortperm partialsortperm! pairs params! params



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(Colorant, desc)
```

Parse a color description.

This parses subset of HTML/CSS color specifications. In particular, everything is supported but: "currentColor".

It does support named colors (though it uses X11 named colors, which are slightly different than W3C named colors in some cases), "rgb()", "hsl()", "#RGB", and "#RRGGBB' syntax.

Args:

  * `Colorant`: literal "Colorant" will parse according to the `desc`

string (usually returning an `RGB`); any more specific choice will return a color of the specified type.

  * `desc`: A color name or description.

Returns:   An `RGB{N0f8}` color, unless:     - "hsl(h,s,l)" was used, in which case an `HSL` color;     - "rgba(r,g,b,a)" was used, in which case an `RGBA` color;     - "hsla(h,s,l,a)" was used, in which case an `HSLA` color;     - a specific `Colorant` type was specified in the first argument


In [67]:
Phen

1600-element Array{Float64,1}:
  -1.4979941475738112
 -15.441024571716175 
  -5.56584874548618  
  -3.319975447952978 
 -11.511346649399426 
  -2.4737507140814836
  -6.432555926753944 
   1.829269466953729 
  -6.105638401662253 
  -8.607911188751661 
  -2.5814701656480543
  -1.1683540311990153
  -5.41587033361586  
   ⋮                 
  -5.066482833073634 
 -12.842910359606075 
  -0.713308120713296 
  -5.926553080004514 
  -3.1855047702508603
  -4.720903633237186 
  -1.4974865036440916
 -12.416490101345268 
  -9.467137286311434 
 -24.342215413260845 
  -6.640663744760102 
  -2.48018813481966  

1600×3 Array{Int64,2}:
 1701  1066  1546
 1702   794  1504
 1703   753  1282
 1704  1002  1387
 1705   761  1212
 1706  1041  1664
 1707   801  1518
 1708   745  1547
 1709   743  1400
 1710   774  1204
 1711  1054  1539
 1712   959  1531
 1713  1049  1463
    ⋮            
 3289   746  1422
 3290   981  1404
 3291   765  1344
 3292   786  1587
 3293   808  1695
 3294   745  1600
 3295   706  1586
 3296  1096  1650
 3297   913  1598
 3298   756  1700
 3299   784  1489
 3300   814  1334